### ISSUE TITLE
Update to Elm 0.19

### ISSUE THREAD

**Issue by aforemny** [aforemny/elm-mdc#116]
I updated the library to Elm 0.19 in the [elm-19](https://github.com/aforemny/elm-mdc/tree/elm-19) branch. Before this will become the new master, I want to refactor the library to use the new Dom API, and also to have a second look at the components.

Please let me know if you are using the elm-19 version already, especially if you find any issues.

**Progress**

- [x] Make library compile in 0.19
- [x] Make demo compile in 0.19

**Tasks**
- [ ] Refactor Browser.Dom
- [ ] Refactor components

**Per component tasks:**
- [ ] Button
- [ ] Card
- [ ] Checkbox
- [ ] Chip
- [ ] Dialog
- [ ] Drawer.Permanent
- [ ] Drawer.Persistent
- [ ] Drawer.Temporary
- [ ] Elevation
- [ ] Fab
- [ ] FormField
- [ ] GridList
- [ ] Icon
- [ ] IconToggle
- [ ] ImageList
- [ ] LayoutGrid
- [ ] LinearProgress
- [ ] List
- [ ] Menu
- [ ] Options
- [ ] RadioButton
- [x] Ripple (a5475990ff269347bd24374ece0371a270d19dc7)
- [ ] Select
- [ ] Slider
- [ ] Snackbar
- [ ] Switch
- [ ] Tabs
- [ ] Textfield
- [ ] Textfield
- [ ] Textfield.HelperText
- [ ] Theme
- [ ] Toolbar
- [ ] TopAppBar
- [ ] Typography

**Comment by dpinn** [comment]
That's great! Thanks Alexander. I thought you might run into troubles with kernel code, not that I'm claiming to understand what that means; but I understand that Elm 0.19 doesn't allow it.

**Comment by sorage** [comment]
demo elm version is still 0.19 in elm-package.json

**Comment by aforemny** [comment]
Hi @sorage, the elm version should be 0.19 in the elm-19 branch. It wasn't like that in elm-package.json (which is deprecated), but it is like that in the Elm 0.19-compatible elm.json file. I removed elm-package.json from the branch to avoid confusion. Thanks!

**Comment by berenddeboer** [comment]
Starting new project, wishing you all the best getting this done, as I'm very keen to try out 0.19!

**Comment by dpinn** [comment]
When using the ```--optimize``` flag on the ```elm make``` command, the following error message appears:

```
-- DEBUG REMNANTS --------------------------------------------------------------

There are uses of the `Debug` module in the following modules:

    Internal.Ripple.Implementation

But the --optimize flag only works if all `Debug` functions are removed!

Note: The issue is that --optimize strips out info needed by `Debug` functions.
Here are two examples:

    (1) It shortens record field names. This makes the generated JavaScript is
    smaller, but `Debug.toString` cannot know the real field names anymore.

    (2) Values like `type Height = Height Float` are unboxed. This reduces
    allocation, but it also means that `Debug.toString` cannot tell if it is
    looking at a `Height` or `Float` value.

There are a few other cases like that, and it will be much worse once we start
inlining code. That optimization could move `Debug.log` and `Debug.todo` calls,
resulting in unpredictable behavior. I hope that clarifies why this restriction
exists!

```

**Comment by wscherphof** [comment]
Started using 0.19, love the project 👍 So far:

- Saw styles failing of `Textfield.box` and `Textfield.outlined`
- Failing to import `Snackbar`, see #129

**Comment by aforemny** [comment]
@dpinn Hi David, sorry I haven't had the time to check that one yet. Does that happen when you try to compile the demo, or a program that uses this library? Because the demo is not expected to be `--optimize`-friendly, I do use `Debug.log` purposefully in some places. If that occurs to you in an application that uses the library, please open an issue. Thanks!

@wscherphof Hi! Happy you seem to like it. Could you please open an issue for the styling problems relating to `Textfield`?

**Comment by aforemny** [comment]
Current master works in Elm 0.19. Ripple has been refactored to use the new DOM API. In other cases, using the new DOM API was not feasible, because we require getting the bounding client rect of parent or child components which is not as feasible as the ripple case.
